version: "3"

services:
  mysql:
    image: mysql:latest
    container_name: db
    restart: always
    command: --binlog-format=ROW --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:${DB_PORT}"
      - "33060:33060"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"

  directus:
    image: directus/directus:latest
    container_name: admin
    restart: always
    ports:
      - "8055:8055"
    volumes:
      - ./docker/directus/database:/directus/database
      - ./docker/directus/uploads:/directus/uploads
      - ./docker/directus/extensions:/directus/extensions
    environment:
      DB_CLIENT: "mysql"
      DB_HOST: 127.0.0.1
      DB_PORT: "${DB_PORT}"
      DB_DATABASE: "${DB_DATABASE}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      KEY: "${DIRECTUS_KEY}"
      SECRET: "${DIRECTUS_SECRET}"
      ADMIN_EMAIL: "${DIRECTUS_ADMIN_EMAIL}"
      ADMIN_PASSWORD: "${DIRECTUS_ADMIN_PASSWORD}"
      WEBSOCKETS_ENABLED: "true"
    depends_on:
      - mysql

  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: search
    restart: always
    ports:
      - "7700:7700"
    volumes:
      - ./docker/meilisearch:/meili_data
    environment:
      MEILI_MASTER_KEY: "${VITE_MEILI_MASTER_KEY}"

  meilisync:
    image: long2ice/meilisync:latest
    container_name: meilisync
    restart: always
    volumes:
      - ./docker/meilisync/config.yml:/meilisync/config.yml
    environment:
      DB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      DB_DATABASE: "${DB_DATABASE}"
      MEILI_MASTER_KEY: "${VITE_MEILI_MASTER_KEY}"
    depends_on:
      - mysql
      - meilisearch
