version: "3.7"

services:
  mysql:
    image: mysql:latest
    container_name: projectr_db
    restart: always
    command: --binlog-format=ROW --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:${DB_PORT}"
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"

  directus:
    image: directus/directus:latest
    container_name: projectr_admin
    restart: always
    ports:
      - "8055:8055"
    volumes:
      - ./docker/directus/database:/directus/database
      - ./docker/directus/uploads:/directus/uploads
      - ./docker/directus/extensions:/directus/extensions
    environment:
      DB_CLIENT: "mysql"
      DB_HOST: "projectr_db"
      DB_PORT: "${DB_PORT}"
      DB_DATABASE: "${DB_DATABASE}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      KEY: "${DIRECTUS_KEY}"
      SECRET: "${DIRECTUS_SECRET}"
      ADMIN_EMAIL: "${DIRECTUS_ADMIN_EMAIL}"
      ADMIN_PASSWORD: "${DIRECTUS_ADMIN_PASSWORD}"
      WEBSOCKETS_ENABLED: "true"
    depends_on:
      - mysql

  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: projectr_search
    restart: always
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: "${VITE_MEILI_MASTER_KEY}"

  meilisync:
    platform: linux/x86_64
    image: long2ice/meilisync:latest
    container_name: projectr_meilisync
    restart: always
    volumes:
      - ./docker/meilisync/config.yml:/meilisync/config.yml
    depends_on:
      - mysql
      - meilisearch
