version: '3.7'

services:
  mysql:
    image: mysql:5
    container_name: projectr_mysql
    restart: always
    command: --binlog-format=ROW
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'projectrCMS'
      MYSQL_USER: 'chariskiragu'
      MYSQL_PASSWORD: 'secret'

  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: projectr_meilisearch
    restart: always
    ports:
      - "7700:7700"
    volumes:
      - ./docker/meili_data:/meili_data
    environment:
      MEILI_MASTER_KEY: '018db27a-b774-78af-9756-6531be6607a3'

  meilisync:
    image: long2ice/meilisync
    container_name: projectr_meilisync
    restart: always
    volumes:
      - ./docker/meilisync/config.yml:/meilisync/config.yml

volumes:
  meilisearch_data:
