version: '3.7'

services:
  mysql:
    image: mysql:latest
    container_name: projectr_mysql
    restart: always
    command: --binlog-format=ROW --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
      - '33060:33060'
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d:r
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'

  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: projectr_meilisearch
    restart: always
    ports:
      - '7700:7700'
    environment:
      MEILI_MASTER_KEY: '${VITE_MEILI_MASTER_KEY}'

  meilisync:
    image: long2ice/meilisync
    container_name: projectr_meilisync
    restart: always
    volumes:
      - ./docker/meilisync/config.yml:/meilisync/config.yml:r
