debug: true
progress:
  type: file
  path: ./meilisync/progress.json
source:
  type: mysql
  host: host.docker.internal
  port: 3306
  user: root
  password: "75YncgwrIg"
  database: projectrCMS
meilisearch:
  api_url: http://host.docker.internal:7700
  api_key: "018db27a-b774-78af-9756-6531be6607a3"
  insert_size: 1000
  insert_interval: 10
sync:
  - table: tracks
    index: tracks
    pk: id
    full: true
